### ISSUE TITLE
Make changes in web service logic as sakai axis web services replaced with CXF

### ISSUE THREAD

**Issue by ghost** [Jasig/sakai-connector-portlet#17]
Sakai replaced axis web services and replaced with CXF. 
Make the corresponding changes in web service logic.
Sakai JIRA Link:
https://jira.sakaiproject.org/browse/SAK-25678

**Comment by ChristianMurphy** [comment]
@steveswinsburg could this ticket be resolved? It looks like it was addressed by #17.

**Comment by steveswinsburg** [comment]
Yeah in #18 (this is #17 👍 )
